CREATE WAREHOUSE IF NOT EXISTS INTEROPCORE_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS INTEROPCORE;
CREATE SCHEMA IF NOT EXISTS INTEROPCORE.RAW;
CREATE SCHEMA IF NOT EXISTS INTEROPCORE.ANALYTICS;