USE DATABASE INTEROPCORE;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_PATIENTS (
    Id STRING, BIRTHDATE DATE, DEATHDATE DATE, SSN STRING, DRIVERS STRING, PASSPORT STRING,
    PREFIX STRING, FIRST STRING, MIDDLE STRING, LAST STRING, SUFFIX STRING, MAIDEN STRING,
    MARITAL STRING, RACE STRING, ETHNICITY STRING, GENDER STRING, BIRTHPLACE STRING,
    ADDRESS STRING, CITY STRING, STATE STRING, COUNTY STRING, FIPS STRING, ZIP STRING,
    LAT FLOAT, LON FLOAT, HEALTHCARE_EXPENSES FLOAT, HEALTHCARE_COVERAGE FLOAT, INCOME FLOAT
);

CREATE OR REPLACE TABLE RAW_ENCOUNTERS (
    Id STRING, "START" TIMESTAMP_TZ, "STOP" TIMESTAMP_TZ, PATIENT STRING, ORGANIZATION STRING,
    PROVIDER STRING, PAYER STRING, ENCOUNTERCLASS STRING, CODE STRING, DESCRIPTION STRING,
    BASE_ENCOUNTER_COST FLOAT, TOTAL_CLAIM_COST FLOAT, PAYER_COVERAGE FLOAT,
    REASONCODE STRING, REASONDESCRIPTION STRING
);

CREATE OR REPLACE TABLE RAW_CONDITIONS (
    "START" DATE, "STOP" DATE, PATIENT STRING, ENCOUNTER STRING,
    SYSTEM STRING, CODE STRING, DESCRIPTION STRING
);

CREATE OR REPLACE TABLE RAW_PROVIDERS (
    Id STRING, ORGANIZATION STRING, NAME STRING, GENDER STRING, SPECIALITY STRING,
    ADDRESS STRING, CITY STRING, STATE STRING, ZIP STRING, LAT FLOAT, LON FLOAT,
    ENCOUNTERS INTEGER, PROCEDURES INTEGER
);

CREATE OR REPLACE TABLE RAW_ORGANIZATIONS (
    Id STRING, NAME STRING, ADDRESS STRING, CITY STRING, STATE STRING, ZIP STRING,
    LAT FLOAT, LON FLOAT, PHONE STRING, REVENUE FLOAT, UTILIZATION INTEGER
);

CREATE OR REPLACE TABLE RAW_MEDICATIONS (
    "START" DATE, "STOP" DATE, PATIENT STRING, PAYER STRING, ENCOUNTER STRING,
    CODE STRING, DESCRIPTION STRING, BASE_COST FLOAT, PAYER_COVERAGE FLOAT,
    DISPENSES INTEGER, TOTALCOST FLOAT, REASONCODE STRING, REASONDESCRIPTION STRING
);

CREATE OR REPLACE TABLE RAW_ALLERGIES (
    "START" DATE, "STOP" DATE, PATIENT STRING, ENCOUNTER STRING, CODE STRING, SYSTEM STRING,
    DESCRIPTION STRING, TYPE STRING, CATEGORY STRING, REACTION1 STRING, DESCRIPTION1 STRING,
    SEVERITY1 STRING, REACTION2 STRING, DESCRIPTION2 STRING, SEVERITY2 STRING
);