USE DATABASE INTEROPCORE;
USE SCHEMA RAW;

-- Upload patients.csv, encounters.csv, conditions.csv, providers.csv,
-- organizations.csv, medications.csv, allergies.csv to @INTEROPCORE_STAGE
-- via Snowsight's "Add Data" UI before running the COPY INTO statements below.
-- IMPORTANT: run each COPY INTO exactly once. Re-running without a
-- preceding TRUNCATE will duplicate rows.

COPY INTO RAW_PATIENTS
FROM @INTEROPCORE_STAGE/patients.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

COPY INTO RAW_ENCOUNTERS
FROM @INTEROPCORE_STAGE/encounters.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

COPY INTO RAW_CONDITIONS
FROM @INTEROPCORE_STAGE/conditions.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

COPY INTO RAW_PROVIDERS
FROM @INTEROPCORE_STAGE/providers.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

COPY INTO RAW_ORGANIZATIONS
FROM @INTEROPCORE_STAGE/organizations.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

COPY INTO RAW_MEDICATIONS
FROM @INTEROPCORE_STAGE/medications.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

COPY INTO RAW_ALLERGIES
FROM @INTEROPCORE_STAGE/allergies.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;