USE DATABASE INTEROPCORE;
USE SCHEMA RAW;

SELECT 'Patients missing birthdate' AS check_name, COUNT(*) AS failing_rows
FROM RAW_PATIENTS WHERE BIRTHDATE IS NULL
UNION ALL
SELECT 'Patients missing gender', COUNT(*)
FROM RAW_PATIENTS WHERE GENDER IS NULL OR GENDER = ''
UNION ALL
SELECT 'Encounters missing start/stop', COUNT(*)
FROM RAW_ENCOUNTERS WHERE "START" IS NULL OR "STOP" IS NULL
UNION ALL
SELECT 'Conditions missing description', COUNT(*)
FROM RAW_CONDITIONS WHERE DESCRIPTION IS NULL OR DESCRIPTION = ''
UNION ALL
SELECT 'Encounters with unknown patient', COUNT(*)
FROM RAW_ENCOUNTERS e LEFT JOIN RAW_PATIENTS p ON p.Id = e.PATIENT WHERE p.Id IS NULL
UNION ALL
SELECT 'Conditions with unknown patient', COUNT(*)
FROM RAW_CONDITIONS c LEFT JOIN RAW_PATIENTS p ON p.Id = c.PATIENT WHERE p.Id IS NULL
UNION ALL
SELECT 'Conditions with unknown encounter', COUNT(*)
FROM RAW_CONDITIONS c LEFT JOIN RAW_ENCOUNTERS e ON e.Id = c.ENCOUNTER WHERE e.Id IS NULL
UNION ALL
SELECT 'Invalid gender values', COUNT(*)
FROM RAW_PATIENTS WHERE GENDER NOT IN ('M', 'F')
UNION ALL
SELECT 'Invalid encounter class values', COUNT(*)
FROM RAW_ENCOUNTERS
WHERE ENCOUNTERCLASS NOT IN ('ambulatory','outpatient','urgentcare','wellness','emergency','home','inpatient','snf')
UNION ALL
SELECT 'Encounters where stop is before start', COUNT(*)
FROM RAW_ENCOUNTERS WHERE "STOP" < "START"
UNION ALL
SELECT 'Patients with future birthdate', COUNT(*)
FROM RAW_PATIENTS WHERE BIRTHDATE > CURRENT_DATE()
UNION ALL
SELECT 'Duplicate patient IDs', COUNT(*)
FROM (SELECT Id FROM RAW_PATIENTS GROUP BY Id HAVING COUNT(*) > 1)
UNION ALL
SELECT 'Duplicate encounter IDs', COUNT(*)
FROM (SELECT Id FROM RAW_ENCOUNTERS GROUP BY Id HAVING COUNT(*) > 1)
UNION ALL
SELECT 'Providers missing name', COUNT(*)
FROM RAW_PROVIDERS WHERE NAME IS NULL OR NAME = ''
UNION ALL
SELECT 'Organizations missing name', COUNT(*)
FROM RAW_ORGANIZATIONS WHERE NAME IS NULL OR NAME = ''
UNION ALL
SELECT 'Medications missing description', COUNT(*)
FROM RAW_MEDICATIONS WHERE DESCRIPTION IS NULL OR DESCRIPTION = ''
UNION ALL
SELECT 'Allergies missing description', COUNT(*)
FROM RAW_ALLERGIES WHERE DESCRIPTION IS NULL OR DESCRIPTION = ''
UNION ALL
SELECT 'Providers with unknown organization', COUNT(*)
FROM RAW_PROVIDERS p LEFT JOIN RAW_ORGANIZATIONS o ON o.Id = p.ORGANIZATION WHERE o.Id IS NULL
UNION ALL
SELECT 'Medications with unknown patient', COUNT(*)
FROM RAW_MEDICATIONS m LEFT JOIN RAW_PATIENTS p ON p.Id = m.PATIENT WHERE p.Id IS NULL
UNION ALL
SELECT 'Medications with unknown encounter', COUNT(*)
FROM RAW_MEDICATIONS m LEFT JOIN RAW_ENCOUNTERS e ON e.Id = m.ENCOUNTER WHERE e.Id IS NULL
UNION ALL
SELECT 'Allergies with unknown patient', COUNT(*)
FROM RAW_ALLERGIES a LEFT JOIN RAW_PATIENTS p ON p.Id = a.PATIENT WHERE p.Id IS NULL
UNION ALL
SELECT 'Medications where stop is before start', COUNT(*)
FROM RAW_MEDICATIONS WHERE "STOP" < "START"
UNION ALL
SELECT 'Duplicate provider IDs', COUNT(*)
FROM (SELECT Id FROM RAW_PROVIDERS GROUP BY Id HAVING COUNT(*) > 1)
UNION ALL
SELECT 'Duplicate organization IDs', COUNT(*)
FROM (SELECT Id FROM RAW_ORGANIZATIONS GROUP BY Id HAVING COUNT(*) > 1)

ORDER BY failing_rows DESC;